export const ROUTES = {
  WELCOME_1: 'Welcome 1',
  WELCOME_2: 'Welcome 2',
  WELCOME_3: 'Welcome 3',
  WELCOME_4: 'Welcome 4',
  LOGIN: 'Login',
  FORGOT_PASSWORD: 'Forgot Password',
  REGISTER: 'Register',
  ONE_TIME_PASSWORD: 'One Time Password',
  VERIFY_EMAIL: 'Verify Email',

  HOME_NAVIGATOR: 'Home Navigator',
  HOME: 'Home',
  PROPERTY: 'Property',
  PROPERTY_EDIT: 'Property Edit',
  ROOM: 'Room',
  ROOM_EDIT: 'Room Edit',
  WALL_OUTLET: 'Wall Outlet',
  COUNTDOWN: 'Countdown',
  SCHEDULE: 'Schedule',
  ALERT: 'Alert',
  PROFILE: 'Profile',
  EDIT_PROFILE: 'Edit Profile',
  SECURITY: 'Security',

  DATA_NAVIGATOR: 'Data Navigator',
  DATA: 'Data',
  PROPERTY_DATA: 'Property Data',
  ROOM_DATA: 'Room Data',
  WALL_OUTLET_DATA: 'Wall Outlet Data',

  ADD_NAVIGATOR: 'Add Navigator',
  ADD: 'Add',
  ADD_PROPERTY: 'Add Property',
  ADD_ROOM: 'Add Room',
  ADD_WALL_OUTLET: 'Add Wall Outlet',
  SCAN_WALL_OUTLET: 'Scan Wall Outlet',

  VOICE_NAVIGATOR: 'Voice Navigator',
  VOICE: 'Voice',

  NOTIFICATION_NAVIGATOR: 'Notification Navigator',
  NOTIFICATION: 'Notification',
  NOTIFICATION_DETAIL: 'Notification Detail',
}